# pip install deep-translator
# Generates js/main/walajna-i18n-ur.js (var WALAJNA_UR_DICT = {...})
import json
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "js/main/walajna-i18n.js"
text = SRC.read_text(encoding="utf-8")
start = text.index('assignBatch("en", {')
end = text.index('\n  });\n\n  if (typeof WALAJNA_UR_DICT', start)
block = text[start + len('assignBatch("en", {'): end]
pat = re.compile(r'"((?:[^"\\]|\\.)*)":\s*"((?:[^"\\]|\\.)*)"')


def js_decode(raw: str) -> str:
    out = []
    i = 0
    while i < len(raw):
        if raw[i] == "\\" and i + 1 < len(raw):
            n = raw[i + 1]
            if n == "n":
                out.append("\n")
                i += 2
                continue
            if n == "r":
                out.append("\r")
                i += 2
                continue
            if n == "t":
                out.append("\t")
                i += 2
                continue
            if n in "\\\"'":
                out.append(n)
                i += 2
                continue
        out.append(raw[i])
        i += 1
    return "".join(out)


pairs = []
for m in pat.finditer(block):
    pairs.append((js_decode(m.group(1)), js_decode(m.group(2))))

try:
    from deep_translator import GoogleTranslator
except ImportError:
    print("Install: pip install deep-translator", file=sys.stderr)
    sys.exit(1)

tr = GoogleTranslator(source="en", target="ur")
out = {}
for i, (k, v) in enumerate(pairs):
    if not v.strip():
        out[k] = v
        continue
    if v in ("—", "–", "-"):
        out[k] = v
        continue
    if re.fullmatch(r"[\d\s\-/:.]+", v):
        out[k] = v
        continue
    try:
        out[k] = tr.translate(v)
    except Exception as e:
        print("fail", k, e, file=sys.stderr)
        out[k] = v
    time.sleep(0.08)
    if (i + 1) % 50 == 0:
        print(i + 1, "/", len(pairs), flush=True)

# UI labels for language picker (override machine translation)
out["settings.lang.ar"] = "العربية (افتراضي)"
out["settings.lang.en"] = "English"
out["settings.lang.ur"] = "اردو"
out["meta.app"] = "ولجنا"

out_path = ROOT / "js/main/walajna-i18n-ur.js"
body = (
    "/**\n * Full Urdu (ur) strings for Walajna — Arabic script.\n"
    " * Generated by scripts/build_full_ur.py — re-run after changing English i18n.\n */\n"
    "var WALAJNA_UR_DICT = "
    + json.dumps(out, ensure_ascii=False)
    + ";\n"
)
out_path.write_text(body, encoding="utf-8")
print("wrote", out_path, "keys", len(out), flush=True)
