import json
import re
from pathlib import Path

p = Path(__file__).resolve().parent.parent / "js/main/walajna-i18n-ur.js"
text = p.read_text(encoding="utf-8")
start = text.index("var WALAJNA_UR_DICT = ") + len("var WALAJNA_UR_DICT = ")
depth = 0
end = None
for i in range(start, len(text)):
    c = text[i]
    if c == "{":
        depth += 1
    elif c == "}":
        depth -= 1
        if depth == 0:
            end = i + 1
            break
if end is None:
    raise SystemExit("parse fail")
obj = json.loads(text[start:end])
fixed = False
for k, v in list(obj.items()):
    if v is None:
        obj[k] = "#" if "th.no" in k else ""
        fixed = True
# Fix i18n placeholder if translator broke {year}
if obj.get("home.footer") and "{سال}" in obj["home.footer"]:
    obj["home.footer"] = obj["home.footer"].replace("{سال}", "{year}")
    fixed = True
if obj.get("home.footer") and "{year}" not in obj["home.footer"] and "©" in str(obj.get("home.footer")):
    # ensure {year} exists for t() — English had © {year}
    if "ولجنا" in str(obj.get("home.footer", "")) and "{year}" not in str(obj["home.footer"]):
        obj["home.footer"] = "© {year} ولجنا۔ جملہ حقوق محفوظ ہیں۔"
        fixed = True

out = (
    "/**\n * Full Urdu (ur) strings for Walajna — Arabic script.\n"
    " * Generated by scripts/build_full_ur.py — re-run after changing English i18n.\n */\n"
    "var WALAJNA_UR_DICT = "
    + json.dumps(obj, ensure_ascii=False)
    + ";\n"
)
p.write_text(out, encoding="utf-8")
print("fixed", fixed, "keys", len(obj))
